### ISSUE TITLE
Node PoW don't work in the BIT Network

### ISSUE THREAD

**Issue by Thorgrlm** [Enecuum/docs#4]
Hi I'm trying to activate a PoW node in the prove network (BIT Network) but i can see a error a the bit_db and the PoW don't work, someone know whats going on?
Mi OS is ubuntu 18.04
thanks

Bit_db
2020-09-16T12:12:21.145059Z 767 [Note] Aborted connection 767 to db: 'trinity' user: 'root' host: '172.17.0.3' (Got an error reading communication packets)
2020-09-16T12:12:24.716091Z 768 [Note] Aborted connection 768 to db: 'trinity' user: 'root' host: '172.17.0.3' (Got an error reading communication packets)
2020-09-16T12:12:28.165892Z 769 [Note] Aborted connection 769 to db: 'trinity' user: 'root' host: '172.17.0.3' (Got an error reading communication packets)
2020-09-16T12:12:31.846890Z 770 [Note] Aborted connection 770 to db: 'trinity' user: 'root' host: '172.17.0.3' (Got an error reading communication packets)

Bit_pow
[2020.09.16 12:13:34] [INFO]
query peer {"socket":"95.216.246.116:8000","primary":true,"failures":null}
Application started
Loading config from config.json ...
config = {"dbhost":"dbhost","dbname":"trinity","dbuser":"root","dbpass":12345,"loglevel":"info","load":10,"port":0,"difficulty":10,"block_reward":96560000000,"reward_ratio":{"pos":4000,"poa":4000,"pow":1600,"ref":400},"mode":"verify","target_speed":15,"auto_id":true,"ip_api_key":"lcJtjJcHOkN1uDw","explorer":0,"peek_limit":100,"mblock_interval_ms":100,"cashier_interval_ms":10,"cashier_chunk_size":10,"pending_size":10,"poa_hearbeat_interval_ms":250,"poa_min_interval_ms":100,"pending_timeout":5,"tail_timeout":100,"max_tps":9999,"max_mblocks_per_macroblock":3,"max_txs_per_macroblock":9,"max_txs_per_microblock":3,"min_txs_per_microblock":1,"dbport":3306,"transfer_lock":5,"snapshot_interval":1000,"snapshot_file":"snapshot.json","TRUNK":"BITGENESIS","ORIGIN":{"n":0,"publisher":"029dd222eeddd5c3340e8d46ae0a22e2c8e301bfee4903bcf8c899766c8ceb3a7d","nonce":0,"m_root":"","reward":3383481700000000000},"fee_shares":{"gen_share":3000,"pow_share":3000,"ldr_share":0,"pos_share":4000},"stake_limits":{"min_stake":250000000000,"max_stake":10000000000000,"default_stake":0},"stakes":[250000000000,1250000000000,2500000000000,5000000000000,7500000000000,10000000000000],"git_hash":"c6213179c50c3f799af0e36f33c5aa91a90f67c6","_":[],"id":"02a4985a304b71b238bf2750ccc749f46faa664a7da1198b13d4ff6f5902630651","$0":"/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js"}
[2020.09.16 12:13:36] [INFO]
DIFFICULTY set to 10
[2020.09.16 12:13:36] [INFO]
Starting syncer
[2020.09.16 12:13:36] [INFO]
Connected to DB engine, using DB trinity
[2020.09.16 12:13:36] [INFO]
node_id = 02a4985a304b71b238bf2750ccc749f46faa664a7da1198b13d4ff6f5902630651
[2020.09.16 12:13:36] [INFO]
Starting RandomX virtual machine. mode - verify
42
[2020.09.16 12:13:37] [INFO]
query peer {"socket":"95.216.246.116:8000","primary":true,"failures":null}

**Comment by svanurin** [comment]
Hello, PoW is unstable so please wait for new PoW releases in BIT.

**Comment by Thorgrlm** [comment]
ok, thanks you
________________________________
De: Sergey Vanurin <notifications@github.com>
Enviado: miércoles, 3 de febrero de 2021 16:06
Para: Enecuum/docs <docs@noreply.github.com>
Cc: Nest <nestordrs@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Enecuum/docs] Node PoW don't work in the BIT Network (#4)


Hello, PoW is unstable so please wait for new PoW releases in BIT.

**Comment by Thorgrlm** [comment]
Hi, good night, I have 2 miners in my house, can i setup 2 miners in my router?, i have setup the port 7000 for one miner but how to setup the other miner?
________________________________
De: Sergey Vanurin <notifications@github.com>
Enviado: miércoles, 3 de febrero de 2021 16:06
Para: Enecuum/docs <docs@noreply.github.com>
Cc: Nest <nestordrs@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Enecuum/docs] Node PoW don't work in the BIT Network (#4)


Hello, PoW is unstable so please wait for new PoW releases in BIT.

**Comment by svanurin** [comment]
> Hi, good night, I have 2 miners in my house, can i setup 2 miners in my router?, i have setup the port 7000 for one miner but how to setup the other miner?

To change the port you should run pow containter with both ports in _-p_ option and _-e PORT_ option changed to a new port number. like _-p7011:7011_ ... _-e PORT=7011_ and than open 7011 port in your router.

**Comment by Thorgrlm** [comment]
Hello, perfect.. work fine, other question more... can i setup a node pos in a raspberry pi 4 with 8Gb ram?

best regards
________________________________
De: Sergey Vanurin <notifications@github.com>
Enviado: sábado, 20 de febrero de 2021 11:23
Para: Enecuum/docs <docs@noreply.github.com>
Cc: Nest <nestordrs@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Enecuum/docs] Node PoW don't work in the BIT Network (#4)


Hi, good night, I have 2 miners in my house, can i setup 2 miners in my router?, i have setup the port 7000 for one miner but how to setup the other miner?

To change the port you should run pow containter with both ports in -p option and -e PORT option changed to a new port number. like -p7011:7011 ... -e PORT=7011 and than open 7011 port in your router.

**Comment by Thorgrlm** [comment]
hi, good morning, how i can to delete the logs files of the container?
thanks and sorry by annoyances
________________________________
De: Sergey Vanurin <notifications@github.com>
Enviado: sábado, 20 de febrero de 2021 11:23
Para: Enecuum/docs <docs@noreply.github.com>
Cc: Nest <nestordrs@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Enecuum/docs] Node PoW don't work in the BIT Network (#4)


Hi, good night, I have 2 miners in my house, can i setup 2 miners in my router?, i have setup the port 7000 for one miner but how to setup the other miner?

To change the port you should run pow containter with both ports in -p option and -e PORT option changed to a new port number. like -p7011:7011 ... -e PORT=7011 and than open 7011 port in your router.

**Comment by Thorgrlm** [comment]
hi again.. how many bandwidth use the node PoW, and PoS?
in a line ADSL of 16Mb of download and 256K of upload the node PoW no work fine

**Comment by svanurin** [comment]
Should work fine with 8 GB RAM, but don't know about ARM processor architecture, 

Command to delete logs: https://guides.enecuum.com/enq/how-to-pos.html#erase-logs

256k upload may be a problem
